In [8]:
import trimesh
import numpy as np

In [13]:
data_dir = '..\\dataset\\raw_data'
for dirname in os.listdir(data_dir):
    dir_path = os.path.join(data_dir, dirname)
    for subdir_name in os.listdir(dir_path):
        subdir_path = os.path.join(dir_path, subdir_name)
        i = 0
        for filename in os.listdir(subdir_path):
            i = i + 1
            path = os.path.join(subdir_path, filename)
            destination_path = path.split("\\")
            destination_path[2] = 'clean_data'
            destination_path[-1] = str(i) + ".stl"
            destination_path = "/".join(destination_path)
            print(destination_path)
            mesh = trimesh.load_mesh(destination_path, "stl")
            print(mesh.edges_unique.shape)

../dataset/clean_data/test/cube/1.stl
(750, 2)
../dataset/clean_data/test/cube/2.stl
(750, 2)
../dataset/clean_data/test/cube/3.stl
(750, 2)
../dataset/clean_data/test/cube/4.stl
(750, 2)
../dataset/clean_data/test/cube/5.stl
(750, 2)
../dataset/clean_data/test/cube/6.stl
(750, 2)
../dataset/clean_data/test/cube/7.stl
(750, 2)
../dataset/clean_data/test/cube/8.stl
(750, 2)
../dataset/clean_data/test/sphere/1.stl
(750, 2)
../dataset/clean_data/test/sphere/2.stl
(750, 2)
../dataset/clean_data/test/sphere/3.stl
(750, 2)
../dataset/clean_data/test/sphere/4.stl
(750, 2)
../dataset/clean_data/test/sphere/5.stl
(750, 2)
../dataset/clean_data/test/sphere/6.stl
(750, 2)
../dataset/clean_data/test/sphere/7.stl
(750, 2)
../dataset/clean_data/test/sphere/8.stl
(750, 2)
../dataset/clean_data/train/cube/1.stl
(750, 2)
../dataset/clean_data/train/cube/2.stl
(750, 2)
../dataset/clean_data/train/cube/3.stl
(750, 2)
../dataset/clean_data/train/cube/4.stl
(750, 2)
../dataset/clean_data/train/cube/5.stl
(

In [ ]:
../dataset/clean_data/train/sphere/16.stl

In [14]:
edges_features = np.zeros((18, 5)) 

In [15]:
edges_features

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [67]:
mesh = trimesh.load_mesh('./t.stl', "stl")
edges =  mesh.edges_unique
faces = mesh.faces
vertices = mesh.vertices
face_angles = mesh.face_angles
face_adjacency = mesh.face_adjacency

In [27]:
face_angles[4][faces[4] == 0]

array([0.78539812])

In [30]:
for i in face_adjacency_edges[2]:
    print(i)

0
3


In [39]:
new_list = list(set([0, 3, 4]).difference([0, 4]))[0]

In [40]:
new_list

3

In [57]:
def get_vertex(edge, face):
    for i in range(len(face)):
        if (face[i] not in edge):
            return i 

In [62]:
angle_features = []
for i in range(len(edges)):
    angle = []
    for face_index in face_adjacency[i]:
        vertex_index = get_vertex(edges[i], faces[face_index])
        angle.append(face_angles[face_index][vertex_index])
    angle_features.append(angle)    

In [64]:
faces

TrackedArray([[6, 7, 5],
              [6, 5, 4],
              [4, 5, 1],
              [4, 1, 0],
              [0, 1, 3],
              [0, 3, 2],
              [2, 3, 7],
              [2, 7, 6],
              [4, 0, 2],
              [4, 2, 6],
              [1, 5, 7],
              [1, 7, 3]], dtype=int64)

In [84]:
mesh.edges_unique_length

TrackedArray([2.00000006, 1.99999988, 2.82842708, 1.99999988, 2.00000006,
              2.        , 2.82842717, 2.82842704, 2.        , 2.00000006,
              2.        , 1.99999988, 2.82842708, 2.82842704, 2.82842717,
              2.        , 1.99999988, 2.00000006])

In [102]:
def d(p, q, r):
    d = (q - p) / np.linalg.norm(q - p)
    v = r - p
    t = np.dot(v, d)
    s = p +  t * d
    return np.linalg.norm(s-r)

In [103]:
vertices

TrackedArray([[ 1.26135695,  2.33049965, -0.4006241 ],
              [ 1.26135695,  2.33049965,  1.59937596],
              [ 1.26135695,  0.33049977, -0.4006241 ],
              [ 1.26135695,  0.33049977,  1.59937596],
              [-0.73864305,  2.33049965, -0.4006241 ],
              [-0.73864305,  2.33049965,  1.59937596],
              [-0.73864305,  0.33049977, -0.4006241 ],
              [-0.73864305,  0.33049977,  1.59937596]])

In [104]:
two_ratios_features = []
for i in range(len(edges)):
    two_ratio = []
    for face_index in face_adjacency[i]:
        vertex_index = get_vertex(edges[i], faces[face_index])
        r = vertices[faces[face_index][vertex_index]]
        p = vertices[edges[i][0]]
        q = vertices[edges[i][1]]
        if (i == 0):
            print(r)
            print(p)
            print(q)
        edge_length = np.linalg.norm(p-q)
        distance = d(p, q, r)
        ratio = distance/ edge_length
        two_ratio.append(ratio)
    two_ratios_features.append(two_ratio) 

[-0.73864305  2.33049965 -0.4006241 ]
[ 1.26135695  2.33049965 -0.4006241 ]
[1.26135695 2.33049965 1.59937596]
[1.26135695 0.33049977 1.59937596]
[ 1.26135695  2.33049965 -0.4006241 ]
[1.26135695 2.33049965 1.59937596]


In [105]:
edges[0]

array([0, 1], dtype=int64)

In [106]:
two_ratios_features

[[0.9999999701976785, 0.9999999105930355],
 [1.0000000894069725, 1.0000000596046483],
 [0.49999999999999806, 0.49999999999999806],
 [1.0000000894069725, 1.0000000596046483],
 [0.9999999105930355, 0.9999999701976785],
 [1.0000000298023224, 0.9999999403953552],
 [0.4999999999999998, 0.4999999999999998],
 [0.4999999999999991, 0.49999999999999906],
 [1.0000000298023224, 0.9999999403953552],
 [0.9999999105930355, 0.9999999701976785],
 [1.0000000298023224, 0.9999999403953552],
 [1.0000000894069725, 1.0000000596046483],
 [0.49999999999999806, 0.49999999999999806],
 [0.49999999999999906, 0.4999999999999991],
 [0.4999999999999998, 0.4999999999999998],
 [1.0000000298023224, 0.9999999403953552],
 [1.0000000894069725, 1.0000000596046483],
 [0.9999999105930355, 0.9999999701976785]]

In [24]:
print(mesh.edges_face)

[ 0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7
  8  8  8  9  9  9 10 10 10 11 11 11]


In [2]:
from data_preprocess.data_reader import tfrecord_to_dataset, dataset_to_tfrecord

In [3]:
features, labels = tfrecord_to_dataset('./dataset/encoded_data/train.tfrecord')

In [4]:
for key, value in features.items():
    print("Key: {}, Shape: {}".format(key, value.sha))

In [5]:
s

[(40,),
 (40,),
 (40, 252, 3),
 (40, 500, 3),
 (40, 750, 2),
 (40, 750),
 (40, 500, 3),
 (40, 750, 2)]

In [125]:
features['vertices']

(40, 252, 3)

In [6]:
import numpy as np

In [14]:
x = np.array([[[0, 1, 8], [2, 3, 9]], [[4, 5, 10], [6, 7, 11]], [[4, 5, 10], [9, 8, 10]]])

In [16]:
x

array([[[ 0,  1,  8],
        [ 2,  3,  9]],

       [[ 4,  5, 10],
        [ 6,  7, 11]],

       [[ 4,  5, 10],
        [ 9,  8, 10]]])

In [18]:
m = np.mean(x, 1)
m

array([[ 1. ,  2. ,  8.5],
       [ 5. ,  6. , 10.5],
       [ 6.5,  6.5, 10. ]])

In [25]:
y = np.reshape(m, (-1, 1, x.shape[2]))

In [26]:
y

array([[[ 1. ,  2. ,  8.5]],

       [[ 5. ,  6. , 10.5]],

       [[ 6.5,  6.5, 10. ]]])

In [39]:
new = x - y
new[2][0][1] = -3
new

array([[[-1. , -1. , -0.5],
        [ 1. ,  1. ,  0.5]],

       [[-1. , -1. , -0.5],
        [ 1. ,  1. ,  0.5]],

       [[-2.5, -3. ,  0. ],
        [ 2.5,  1.5,  0. ]]])

In [40]:
max = np.max(abs(new), 1)
max = np.reshape(max, (-1, 1, new.shape[2]))
c = np.divide(new, max, out=np.zeros_like(new), where=max!=0)
c

array([[[-1. , -1. , -1. ],
        [ 1. ,  1. ,  1. ]],

       [[-1. , -1. , -1. ],
        [ 1. ,  1. ,  1. ]],

       [[-1. , -1. ,  0. ],
        [ 1. ,  0.5,  0. ]]])

In [75]:
x = features['vertices'][0]
x[:5]

array([[6.8672001e-02, 7.6192588e-01, 7.0866615e-01],
       [1.5671299e-01, 7.6258004e-02, 5.2401237e-04],
       [9.4284803e-01, 8.5998398e-01, 2.4471402e-03],
       [3.5383299e-01, 1.0053520e+00, 4.8487164e-02],
       [7.5063300e-01, 2.0155892e-02, 6.5847200e-01]], dtype=float32)

In [104]:
y = features['face_adjacency'][0]

In [106]:
s = [i.shape for i in features['face_adjacency']]

In [24]:
from sklearn import preprocessing

In [76]:
mean = np.mean(features['vertices'][0], 0)
max = np.max(features['vertices'][0], 0)
max.shape

(3,)

In [77]:
normalized = (x - mean) / max

In [95]:
mesh = trimesh.Trimesh(vertices=x,
                       faces=y)

In [84]:
mesh = trimesh.load_mesh('./dataset/clean_data/train/cube/1.stl')

In [36]:
import numpy as np

In [37]:
a = np.array([[1, 2], [3, 4]])

In [46]:
mean = np.mean(a, 0)
mean

array([2., 3.])

In [47]:
max = np.max(a, 0)

In [48]:
max

array([3, 4])

In [50]:
(a - mean) / max

array([[-0.33333333, -0.25      ],
       [ 0.33333333,  0.25      ]])

In [42]:
features['face_adjacency'].shape

(40, 750, 2)